project(private-frameworks)

# this is mainly for frameworks that are required for Security,
# since Security is built for both CLI and GUI
if (COMPONENT_cli OR COMPONENT_dev_gui_common)
	set(CMAKE_INSTALL_DEFAULT_COMPONENT_NAME "cli_gui_common")

	# these are also stubs, but they're needed for Security
	add_subdirectory(AppleAccount)
	add_subdirectory(AppleFSCompression)
	add_subdirectory(AppleSystemInfo)
	add_subdirectory(AuthKit)
	add_subdirectory(ConfigurationProfiles)
	add_subdirectory(CrashReporterSupport)
	add_subdirectory(login)
	add_subdirectory(MobileAsset)
	add_subdirectory(ProtocolBuffer)
	add_subdirectory(TrustedPeers)

	add_subdirectory(DisplayServices)
	add_subdirectory(MonitorPanel)
	add_subdirectory(OSD)

	# required for dtrace and IOKitTools
	add_subdirectory(CoreSymbolication)
endif()

# this is mainly for anything that Xcode requires to run on the CLI
if (COMPONENT_dev_gui_common)
	set(CMAKE_INSTALL_DEFAULT_COMPONENT_NAME "cli_dev_gui_common")

	add_subdirectory(DebugSymbols)
endif()

# same here, except this is for stubs that Xcode needs
if (COMPONENT_dev_gui_stubs_common)
	set(CMAKE_INSTALL_DEFAULT_COMPONENT_NAME "cli_dev_gui_stubs_common")

	add_subdirectory(AppleSauce)
	add_subdirectory(AssetCacheServices)
	add_subdirectory(AssistantServices)
	add_subdirectory(AuthKitUI)
	add_subdirectory(CoreAnalytics)
	add_subdirectory(CoreSimulator)
	add_subdirectory(CoreUI)
	add_subdirectory(DataDetectors)
	add_subdirectory(DataDetectorsCore)
	add_subdirectory(DataDetectorsNaturalLanguage)
	add_subdirectory(DeviceLink)
	add_subdirectory(DiskImages)
	add_subdirectory(DiskManagement)
	add_subdirectory(Espresso)
	add_subdirectory(IconServices)
	add_subdirectory(IOPlatformPluginFamily)
	add_subdirectory(kperf)
	add_subdirectory(LoggingSupport)
	add_subdirectory(MobileDevice)
	add_subdirectory(NetworkStatistics)
	add_subdirectory(PackageKit)
	add_subdirectory(PlugInKit)
	add_subdirectory(PowerLog)
	add_subdirectory(PubSub)
	add_subdirectory(SkyLight)
	add_subdirectory(SpotlightIndex)
	add_subdirectory(StreamingZip)
	add_subdirectory(TCC)
	add_subdirectory(ViewBridge)
endif()

# this is for all the other stubbed frameworks
if (COMPONENT_gui_stubs)
	set(CMAKE_INSTALL_DEFAULT_COMPONENT_NAME "gui_stubs")

	add_subdirectory(AccessibilitySharedUISupport)
	add_subdirectory(AccessibilitySupport)
	add_subdirectory(ActionKit)
	add_subdirectory(ActionKitUI)
	add_subdirectory(AdPlatforms)
	add_subdirectory(AdPlatformsCommon)
	add_subdirectory(AggregateDictionary)
	add_subdirectory(AOSAccounts)
	add_subdirectory(AppSSOCore)
	add_subdirectory(AppStoreUI)
	add_subdirectory(AssertionServices)
	add_subdirectory(AVConference)
	add_subdirectory(BackBoardServices)
	add_subdirectory(Bom)
	add_subdirectory(CardKit)
	add_subdirectory(ClassroomKit)
	add_subdirectory(CloudKitCodeProtobuf)
	add_subdirectory(ContactsMetrics)
	add_subdirectory(CoreCDP)
	add_subdirectory(CoreFollowUp)
	add_subdirectory(CoreParsec)
	add_subdirectory(CoreUtils)
	add_subdirectory(DeauthorizationKit)
	add_subdirectory(DeviceIdentity)
	add_subdirectory(DistributedEvaluation)
	add_subdirectory(FaceTimeTouchBarProtocols)
	add_subdirectory(FontServices)
	add_subdirectory(GenerativeAssistantSettings)
	add_subdirectory(HomeKitFeatures)
	add_subdirectory(IASUtilities)
	add_subdirectory(icloudMCCKit)
	add_subdirectory(IdleTimerServices)
	add_subdirectory(IntentsFoundation)
	add_subdirectory(InternationalSupport)
	add_subdirectory(KerberosHelper)
	add_subdirectory(LinkServices)
	add_subdirectory(LocalAuthenticationRecoveryUI)
	add_subdirectory(Marco)
	add_subdirectory(MediaExperience)
	add_subdirectory(MessagesKit)
	add_subdirectory(NewDeviceOutreachMacUI)
	add_subdirectory(NewsAnalyticsUpload)
	add_subdirectory(NLP)
	add_subdirectory(PerformanceAnalysis)
	add_subdirectory(PhoneNumbers)
	add_subdirectory(QueryParser)
	add_subdirectory(RecapPerformanceTesting)
	add_subdirectory(RTTUtilities)
	add_subdirectory(Suggestions)
	add_subdirectory(SystemAdministration)
	add_subdirectory(ServerInformation)
	add_subdirectory(ShazamCore)
	add_subdirectory(ShazamEvents)
	add_subdirectory(ShazamInsights)
	add_subdirectory(ShazamKitUI)
	add_subdirectory(Spotlight)
	add_subdirectory(SpotlightDaemon)
	add_subdirectory(SpotlightReceiver)
	add_subdirectory(SpotlightServerKit)
	add_subdirectory(SpotlightServices)
	add_subdirectory(StocksKit)
	add_subdirectory(SyncedDefaults)
	add_subdirectory(SystemUIPlugin)
	add_subdirectory(TextComposer)
	add_subdirectory(TextInputUI)
	add_subdirectory(TextToSpeechVoiceBankingUI)
	add_subdirectory(Timeline)
	add_subdirectory(TimeMachine)
	add_subdirectory(TimeSync)
	add_subdirectory(UIFoundation)
	add_subdirectory(UserActivity)
endif()
