#!/bin/sh
# Generate the Darwin Clang module for the private SDK.
# Membership is exactly the textual include closure of a curated umbrella of public libc/POSIX/Mach headers;
# every other header under usr/include (not owned by the objc/dispatch/os module maps) is `exclude header`,
# so including it stays textual instead of importing a Darwin module that doesn't contain it.
set -u

root=$(cd "$(dirname "$0")/.." && pwd)
T="$root/toolchain-linux/swift-6.3.3-RELEASE-ubuntu24.04-aarch64/usr/bin"
export LD_LIBRARY_PATH="$root/toolchain-linux/compat-lib"
S="$root/sdk/MacOSX.sdk"
I="$S/usr/include"
W="$root/tests/clangmod/darwin-gen"
log="$root/logs/darwin-module-gen.log"
rm -rf "$W"
mkdir -p "$W"
: > "$log"

curated="AvailabilityMacros.h Availability.h TargetConditionals.h sys/cdefs.h sys/types.h stdio.h stdlib.h string.h strings.h
unistd.h errno.h fcntl.h math.h time.h sys/time.h pthread.h signal.h inttypes.h limits.h ctype.h locale.h xlocale.h wchar.h
wctype.h dirent.h sys/stat.h sys/mman.h sys/socket.h sys/un.h netinet/in.h arpa/inet.h netdb.h sys/sysctl.h mach/mach.h
mach/mach_time.h dlfcn.h sys/utsname.h termios.h poll.h sys/select.h sys/event.h spawn.h malloc/malloc.h fnmatch.h glob.h
sys/wait.h sys/resource.h sys/ioctl.h sys/param.h sys/uio.h syslog.h setjmp.h pwd.h grp.h libgen.h utime.h sys/file.h
sys/mount.h sys/xattr.h copyfile.h sched.h semaphore.h stdatomic.h libkern/OSByteOrder.h libkern/OSAtomic.h mach-o/dyld.h
os/base.h os/availability.h os/lock.h"
: > "$W/umbrella.txt"
for h in $curated; do
	[ -e "$I/$h" ] || continue
	printf '#include <%s>\nint darling_probe;\n' "$h" > "$W/probe.c"
	if "$T/clang" -target arm64-apple-macosx26.0 -isysroot "$S" -fsyntax-only -w "$W/probe.c" > /dev/null 2>&1; then
		echo "$h" >> "$W/umbrella.txt"
	else
		echo "skip (doesn't compile standalone): $h" >> "$log"
	fi
done

i=0
while [ $i -lt 30 ]; do
	i=$((i + 1))
	{ echo '/* Umbrella for the Darwin Clang module (private Swift-overlay build SDK); generated by gen-darwin-module.sh. */'
	  sed 's/.*/#include <&>/' "$W/umbrella.txt"; } > "$I/_DarlingDarwin.h"
	err=$("$T/clang" -target arm64-apple-macosx26.0 -isysroot "$S" -fsyntax-only -w -x c "$I/_DarlingDarwin.h" 2>&1 | grep -m1 ' error: ')
	[ -z "$err" ] && break
	echo "conflict: $err" >> "$log"
	last=$(tail -1 "$W/umbrella.txt")
	sed -i '$d' "$W/umbrella.txt"
	echo "dropped (last added): $last" >> "$log"
done

# Closure of headers textually included by the umbrella (paths relative to usr/include).
"$T/clang" -target arm64-apple-macosx26.0 -isysroot "$S" -fsyntax-only -w -H -x c "$I/_DarlingDarwin.h" 2>&1 \
	| grep -E '^\.+ ' | sed -E 's/^\.+ //' | grep "^$I/" | sed "s#^$I/##" | sort -u > "$W/closure.txt"
echo "_DarlingDarwin.h" >> "$W/closure.txt"
sort -u -o "$W/closure.txt" "$W/closure.txt"
echo "umbrella headers: $(wc -l < "$W/umbrella.txt"), closure: $(wc -l < "$W/closure.txt")" >> "$log"

owned='^(objc/|dispatch/|os/(log|activity|signpost)\.h$)'
(cd "$I" && find . -name '*.h' | sed 's#^\./##' | grep -vE "$owned" | sort -u) > "$W/all.txt"
grep -E "$owned" "$W/closure.txt" | sed 's/^/closure reaches module-owned header: /' >> "$log"

{ echo 'module Darwin [system] [extern_c] {'
  echo '  umbrella header "_DarlingDarwin.h"'
  # Like Apple's SDK, MacTypes is an explicit submodule: its typedefs (e.g. Duration) must not leak into `import Darwin`.
  echo '  module MacTypes {'
  echo '    header "MacTypes.h"'
  echo '    export *'
  echo '  }'
  comm -23 "$W/all.txt" "$W/closure.txt" | grep -vx MacTypes.h | sed 's/.*/  exclude header "&"/'
  echo '  export *'
  echo '}'
} > "$I/module.modulemap"
echo "excluded headers: $(grep -c 'exclude header' "$I/module.modulemap")" >> "$log"
echo DONE >> "$log"
